module.exports.UPDATE_DEVICE_STATUS = 'UPDATE_DEVICE_STATUS';
module.exports.UPDATE_DEVICE_STATUS_BY_PUSH = 'UPDATE_DEVICE_STATUS_BY_PUSH';
module.exports.CONTROL_DEVICE_DATA = 'CONTROL_DEVICE_DATA';
module.exports.UPDATE_DEVICE_DATA_BY_PUSH = 'UPDATE_DEVICE_DATA_BY_PUSH';
module.exports.UPDATE_DEVICE_DATA_MAP = 'UPDATE_DEVICE_DATA_MAP';
module.exports.UPDATE_PRODUCT_INFO_MAP = 'UPDATE_PRODUCT_INFO_MAP';
module.exports.UPDATE_DEVICE_LIST = 'UPDATE_DEVICE_LIST';
module.exports.UPDATE_SHARE_DEVICE_LIST = 'UPDATE_SHARE_DEVICE_LIST';
module.exports.CLEAR_DEVICE_AND_PRODUCT_DATA = 'CLEAR_DEVICE_AND_PRODUCT_DATA';

module.exports.UPDATE_WIFI_LIST = 'UPDATE_WIFI_LIST';
module.exports.RESET_WIFI_LIST = 'RESET_WIFI_LIST';
