exports.UPDATE_DEVICE_STATUS = 'UPDATE_DEVICE_STATUS';
exports.UPDATE_DEVICE_STATUS_BY_PUSH = 'UPDATE_DEVICE_STATUS_BY_PUSH';
exports.CONTROL_DEVICE_DATA = 'CONTROL_DEVICE_DATA';
exports.UPDATE_DEVICE_DATA_BY_PUSH = 'UPDATE_DEVICE_DATA_BY_PUSH';
exports.UPDATE_DEVICE_DATA_MAP = 'UPDATE_DEVICE_DATA_MAP';
exports.UPDATE_PRODUCT_INFO_MAP = 'UPDATE_PRODUCT_INFO_MAP';
exports.UPDATE_DEVICE_LIST = 'UPDATE_DEVICE_LIST';